// WIREFRAME_ONLY — static placeholder content for the Wealth Copilot wireframe.
// Fictional conversation and canned suggestions. Not a real assistant, nothing
// is sent to or generated by any model on device. Replaced by an authoritative
// conversational service in a later task; none of this is financial advice.

export type CopilotRole = "customer" | "copilot";

export type CopilotMessage = { id: string; role: CopilotRole; text: string };

export type CopilotAction = { id: string; title: string; body: string; cta: string };

export const COPILOT_WIREFRAME = {
  kind: "WIREFRAME_ONLY",

  copilot: {
    name: "Wealth Copilot",
    tagline: "Ask about your goals, portfolio, and projections in plain language.",
    initials: "WC",
  },

  messages: [
    {
      id: "m1",
      role: "customer",
      text: "How am I tracking against my retirement goal?",
    },
    {
      id: "m2",
      role: "copilot",
      text: "Your retirement corpus is 46% funded and on track for 2041 at your current pace.",
    },
    {
      id: "m3",
      role: "customer",
      text: "What if I add a ₹10,000 monthly SIP?",
    },
    {
      id: "m4",
      role: "copilot",
      text: "That extra SIP could bring your target date forward and lift the projected corpus. Want to see the projection?",
    },
  ] as CopilotMessage[],

  actions: [
    {
      id: "a1",
      title: "Retirement projection with a new SIP",
      body: "Preview how a ₹10,000 monthly SIP reshapes your funding curve and target year.",
      cta: "See the projection",
    },
    {
      id: "a2",
      title: "Rebalance suggestion",
      body: "Your equity share has drifted above your target band. Review a one-tap rebalance.",
      cta: "Review rebalance",
    },
  ] as CopilotAction[],

  suggestedPrompts: [
    "Am I saving enough each month?",
    "Explain my portfolio allocation",
    "How risky is my current mix?",
    "When can I retire comfortably?",
  ] as string[],
} as const;
