import { describe, it, expect, vi } from 'vitest';
import { executeCoach, type CoachTools } from './engine.js';
import { coachQueryPlanSchema, continuePlan, resolvePeriod, normalizeMerchant, type CoachContext } from './plan.js';
import { calculate, explanationIsGrounded, type FinancialTransaction } from './finance.js';
import type { CoachModel } from './model.js';
const row = (patch: Partial<FinancialTransaction> = {}): FinancialTransaction => ({ id: 'tx1', accountId: 'a1', cardId: null, kind: 'account', amount: '100.10', currency: 'INR', direction: 'debit', status: 'completed', category: 'food', merchant: 'Swiggy UPI', description: 'purchase', transactionAt: '2026-09-10T10:00:00Z', sourceEnvironment: 'demo', dataAsOf: '2026-09-21T08:00:00Z', ownTransfer: false, cardRepayment: false, ...patch });
function dependencies(plan: unknown, rows = [row()]) {
    const model: CoachModel = { plan: vi.fn().mockResolvedValue(plan), explain: vi.fn().mockResolvedValue({ explanation: 'Matching data is shown below.', suggestedPrompts: ['Show me the transactions'] }) };
    const tools: CoachTools = { assertScope: vi.fn().mockResolvedValue(undefined), getAccounts: vi.fn().mockResolvedValue([]), getGoals: vi.fn().mockResolvedValue([]), getTransactions: vi.fn().mockResolvedValue({ rows, truncated: false }) };
    return { model, tools };
}
const input = { userId: 'user1', question: 'Where did I spend the most?', consent: true, history: [] };
describe('query validation', () => {
    it.each([{ intent: 'sql', sql: 'select * from users' }, { intent: 'transaction_search', limit: 10000 }, { intent: 'transaction_search', filters: { status: 'garbage' } }, { intent: 'transaction_search', period: { relative: 'custom', from: '2026-09-30', to: '2026-09-01' } }, { intent: 'transaction_search', filters: { minimumAmount: '1e9' } }])('rejects unsupported plans %j', p => expect(coachQueryPlanSchema.safeParse(p).success).toBe(false));
    it('uses India-local month boundaries including leap years', () => { expect(resolvePeriod({ relative: 'previous_month' }, new Date('2024-03-01T00:00:00Z'))).toMatchObject({ from: '2024-02-01', to: '2024-02-29' }); expect(resolvePeriod(undefined, new Date('2026-08-31T20:00:00Z')).from).toBe('2026-09-01'); });
    it('normalizes merchant variants', () => expect(['SWIGGY*BANGALORE', 'SWIGGY LIMITED', 'Swiggy UPI'].map(normalizeMerchant)).toEqual(['swiggy', 'swiggy', 'swiggy']));
});
describe('Coach execution', () => {
    it('asks for consent before invoking any personal tool', async () => { const { model, tools } = dependencies({ intent: 'category_breakdown' }); const result = await executeCoach({ ...input, consent: false }, model, tools); expect(result.payload).toMatchObject({ consentRequired: true }); expect(tools.getTransactions).not.toHaveBeenCalled(); expect(tools.assertScope).not.toHaveBeenCalled(); });
    it('education never retrieves financial data even without consent', async () => { const { model, tools } = dependencies({ intent: 'education' }); await executeCoach({ ...input, consent: false, question: 'What is compound interest?' }, model, tools); expect(tools.assertScope).not.toHaveBeenCalled(); expect(tools.getAccounts).not.toHaveBeenCalled(); expect(tools.getTransactions).not.toHaveBeenCalled(); });
    it('fresh transaction request cannot fall back to a goal', async () => { const { model, tools } = dependencies({ intent: 'recent_transactions', period: { relative: 'all_available' } }); const result = await executeCoach({ ...input, question: 'Show me the transactions' }, model, tools); expect(result.verified?.transactions[0].id).toBe('tx1'); expect(tools.getGoals).not.toHaveBeenCalled(); });
    it('retains focused category and period for transaction follow-ups', async () => { const previous: CoachContext = { answerId: 'answer1', plan: coachQueryPlanSchema.parse({ intent: 'category_breakdown', filters: { accountIds: ['a1'] } }), period: { from: '2026-09-01', to: '2026-09-21', label: 'September' }, category: 'food', transactionIds: ['tx1'] }; const plan = { intent: 'transaction_search', followUpOf: 'answer1', inherit: ['period', 'category', 'accounts'] }; const { model, tools } = dependencies(plan); const result = await executeCoach({ ...input, question: 'Show me those', previous }, model, tools); expect(result.plan.filters).toMatchObject({ categories: ['food'], accountIds: ['a1'] }); expect(result.verified?.period.from).toBe('2026-09-01'); });
    it('does not carry a previous goal into a new transaction question', () => { const previous: CoachContext = { answerId: 'goalAnswer', plan: coachQueryPlanSchema.parse({ intent: 'goal_progress', goalId: 'g1' }), period: resolvePeriod(), goalId: 'g1', transactionIds: [] }; expect(continuePlan({ intent: 'transaction_search' }, previous).goalId).toBeUndefined(); });
    it('rejects a fabricated follow-up reference', () => expect(() => continuePlan({ intent: 'transaction_search', followUpOf: 'unknown', inherit: ['category'] })).toThrow());
    it('validates the plan before calling tools', async () => { const { model, tools } = dependencies({ intent: 'delete_all' }); await expect(executeCoach(input, model, tools)).rejects.toMatchObject({ code: 'INVALID_QUERY_PLAN' }); expect(tools.getTransactions).not.toHaveBeenCalled(); });
    it('propagates authorization failures', async () => { const { model, tools } = dependencies({ intent: 'transaction_search', filters: { accountIds: ['someone-else'] } }); vi.mocked(tools.assertScope).mockRejectedValue(new Error('Forbidden')); await expect(executeCoach(input, model, tools)).rejects.toThrow('Forbidden'); expect(tools.getTransactions).not.toHaveBeenCalled(); });
    it('does not replace a database failure with zero or fixtures', async () => { const { model, tools } = dependencies({ intent: 'spending_summary' }); vi.mocked(tools.getTransactions).mockRejectedValue(new Error('DB unavailable')); await expect(executeCoach(input, model, tools)).rejects.toMatchObject({ code: 'FINANCIAL_DATA_UNAVAILABLE' }); expect(model.explain).not.toHaveBeenCalled(); });
    it('retains verified evidence when Gemini writer fails', async () => { const { model, tools } = dependencies({ intent: 'category_breakdown' }); vi.mocked(model.explain).mockRejectedValue(new Error('Model unavailable')); const result = await executeCoach(input, model, tools); expect(result.content).toContain('100.10'); expect(result.payload).toMatchObject({ modelStatus: 'verified-fallback', chart: [{ label: 'food', amount: '100.10' }], sources: [{ transactionIds: ['tx1'] }] }); });
    it('does not present no results as established zero spending', async () => { const { model, tools } = dependencies({ intent: 'transaction_search' }, []); vi.mocked(model.explain).mockRejectedValue(new Error()); const result = await executeCoach(input, model, tools); expect(result.content).toContain('No matching transactions'); expect(result.content).not.toContain('₹0'); });
    it('locks selected screen scope against planner expansion', async () => { const { model, tools } = dependencies({ intent: 'transaction_search', filters: { accountIds: ['a2'] } }); const result = await executeCoach({ ...input, scope: { accountId: 'a1' } }, model, tools); expect(result.plan.filters.accountIds).toEqual(['a1']); });
});
describe('deterministic finance', () => {
    it('calculates exact minor units and excludes non-spending', () => { const v = calculate(coachQueryPlanSchema.parse({ intent: 'category_breakdown' }), resolvePeriod(), [row(), row({ id: 'tx2', amount: '0.20' }), row({ status: 'failed', amount: '900' }), row({ direction: 'credit', amount: '900' }), row({ ownTransfer: true, amount: '900' }), row({ cardRepayment: true, amount: '900' })]); expect(v.totalDebit).toBe('100.30'); expect(v.transactionCount).toBe(2); expect(v.merchantTotals[0].label).toBe('swiggy'); });
    it('calculates period comparison without model arithmetic', () => { const v = calculate(coachQueryPlanSchema.parse({ intent: 'spending_comparison' }), resolvePeriod(), [row({ amount: '150' })], [], [], { period: resolvePeriod({ relative: 'previous_month' }), rows: [row({ amount: '100' })] }); expect(v.comparison).toMatchObject({ difference: '50.00', percentage: '50.00' }); });
    it('does not divide by zero when comparison data is absent', () => { const v = calculate(coachQueryPlanSchema.parse({ intent: 'spending_comparison' }), resolvePeriod(), [row()], [], [], { period: resolvePeriod(), rows: [] }); expect(v.comparison?.percentage).toBeNull(); });
    it('does not permit invented amounts in the explanation', () => { const v = calculate(coachQueryPlanSchema.parse({ intent: 'transaction_search' }), resolvePeriod(), [row()]); expect(explanationIsGrounded('You spent ₹100.10', v)).toBe(true); expect(explanationIsGrounded('You spent ₹987654', v)).toBe(false); });
    it('simulates persisted goals without assumed returns', () => { const v = calculate(coachQueryPlanSchema.parse({ intent: 'goal_simulation', monthlyContribution: '1000' }), resolvePeriod(), [], [], [{ id: 'g', title: 'Travel', targetAmount: '3500', currentAmount: '1000', monthlyContribution: '100', targetDate: null, updatedAt: new Date().toISOString() }]); expect(v.goals[0].monthsToTarget).toBe('3'); });
});
